version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-app

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
#   ApplicationStop:
#     - location: ./scripts/app-stop
#       timeout: 10
#       runas: ec2-user

#   AfterInstall:
#     - location: ./scripts/install-pkgs
#       timeout: 1200
#       runas: ec2-user

  ApplicationStart:
    - location: ./scripts/app-start
      timeout: 60
      runas: ec2-user

  # ValidateService:
  #   - location: ./scripts/app-validate
  #     timeout: 10
  #     runas: ec2-user
